"""Worker configurations for distributed orchestration."""

from .worker_configs import (
    ALL_WORKERS,
    API_DESIGNER,
    CODE_REVIEWER,
    CODE_WRITER,
    DATA_ANALYST,
    DATA_WORKERS,
    DATABASE_SPECIALIST,
    DEVOPS_ENGINEER,
    DOC_WRITER,
    INFRASTRUCTURE_WORKERS,
    RESEARCHER,
    SECURITY_AUDITOR,
    SECURITY_WORKERS,
    SOFTWARE_DEV_WORKERS,
    STATISTICAL_MODELER,
    TEST_WRITER,
)

__all__ = [
    # Individual workers
    "DATA_ANALYST",
    "STATISTICAL_MODELER",
    "CODE_WRITER",
    "TEST_WRITER",
    "DOC_WRITER",
    "CODE_REVIEWER",
    "DEVOPS_ENGINEER",
    "API_DESIGNER",
    "SECURITY_AUDITOR",
    "DATABASE_SPECIALIST",
    "RESEARCHER",
    # Worker groups
    "ALL_WORKERS",
    "SOFTWARE_DEV_WORKERS",
    "DATA_WORKERS",
    "INFRASTRUCTURE_WORKERS",
    "SECURITY_WORKERS",
]
